version: 0.2
       
env:
  parameter-store:
    LOGIN_USERID: "docker-userid"
    LOGIN_PASSWORD: "docker-password"
    BUILD_JOBS: "docker-build-jobs"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login -u $LOGIN_USERID -p $LOGIN_PASSWORD
  build:
    commands:
      - echo Start building latest evt...
      - cd Docker && docker build . -t everitoken/evt:latest --build-arg bjobs=$BUILD_JOBS
  post_build:
    commands:
      - echo Publish to Docker Hub...
      - docker push everitoken/evt:latest
