version: 0.2

env:
  parameter-store:
    BEARCHAT_CHANNEL: "bearchat-codebuild-channel"

phases:
  pre_build:
    commands:
      - echo Cloning submodules...
      - git submodule update --init
  build:
    commands:
      - echo Generating build files...
      - mkdir build && cd build
      - cmake ../ -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DSecp256k1_ROOT_DIR=/usr/local -DENABLE_MONGODB_SUPPORT=ON -DENABLE_BIND_LIBRARIES=ON
      - echo Building...
      - ninja -j$(nproc) all
  post_build:
    commands:
      - echo Runing tests
      - ninja test
    finally:
      - echo Posting build results
      - URL="https://${AWS_REGION}.console.aws.amazon.com/codebuild/home?region=${AWS_REGION}#/builds/${CODEBUILD_BUILD_ID}/view/new"
      - curl "${BEARCHAT_CHANNEL}" -H "Content-Type:application/json" -d "{\"text\":\"latest EVT built finished\",\"markdown\":true,\"channel\":\"evt-awscodebuild\",\"attachments\":[{\"text\":\"$URL\",\"url\":\"$URL\"}]}"
 