version: "3"

services:
  evtd:
    build:
      context: .
    image: everitoken/evt:latest
    command: /opt/evt/bin/evtd.sh --data-dir /opt/evt/data
    hostname: evtd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - evtd-data-volume:/opt/evt/data

  evtwd:
    image: everitoken/evt:latest
    command: /opt/evt/bin/evtwd --wallet-dir /opt/evt/data --http-server-address=127.0.0.1:9999
    hostname: evtwd
    links:
      - evtd
    volumes:
      - evtwd-data-volume:/opt/evt/data

volumes:
  evtd-data-volume:
    external: true
  evtwd-data-volume:
    external: true
